### ISSUE TITLE
建议提供控制首次是否自动刷新的选项。provide an arg to controll the first auto load

### ISSUE THREAD

**Issue by yintaibing** [fluttercandies/loading_more_list#15]
如果列表外层使用官方的RefreshIndicator进行包裹，首次加载显示的是LoadingMoreList的loading indicator，而不是RefreshIndicator的loading indicator

**Comment by zmtzawqlp** [comment]
全屏loading状态，你可以返回个空的container？

**Comment by yintaibing** [comment]
> 全屏loading状态，你可以返回个空的container？

这样做，UI效果是达到了，但是仍会自动触发加载请求，期望最好是UI+业务请求都可以自行控制触发。

**Comment by zmtzawqlp** [comment]
autorefresh flase?

**Comment by zmtzawqlp** [comment]
或者你在loadmorebase里面自己控制呗。第一次。把自动的return掉

**Comment by yintaibing** [comment]
嗯嗯，如能实现，不胜感激！

**Comment by zmtzawqlp** [comment]
不是有属性吗

**Comment by zmtzawqlp** [comment]
记错了，有autoLoadMore属性。。不过你可以在loadmorebase里面自己控制一下。
