### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by oliver92** [fluttercandies/loading_more_list#16]
Do you plan on adding web support?

**Comment by zmtzawqlp** [comment]
is there any problem in web?

**Comment by oliver92** [comment]
I think you just need to add support for it in your pubspec

**Comment by zmtzawqlp** [comment]
web is already in flutter sdk, you can build it without any other operation

**Comment by oliver92** [comment]
I see... However i do get an exception this is it:
<code>
The following UnsupportedError was thrown building IndicatorWidget(dirty):
Unsupported operation: Platform._operatingSystem

package:loading_more_list/src/indicator_widget.dart 165:21                            getIndicator
package:loading_more_list/src/indicator_widget.dart 65:22                             build
</code>

Is there a way to make Platform. work on web?

Oliver
