### ISSUE TITLE
AnimatedList support

### ISSUE THREAD

**Issue by wyzard** [fluttercandies/loading_more_list#17]
Thank you for this awesome development.
Is it possible to apply your solution to AnimatedList?

I have to development a list with animations (if it possible with your lib), but If I understand correctly, right now I cannot achieve this. Is it correct?

Thank you for your answer.

**Comment by zmtzawqlp** [comment]
AnimatedList is also a CustomScrollView or SliverAnimatedList.

https://github.com/flutter/flutter/blob/fcb40a05bbc5b4ba08e5360d074ac8407f4c0463/packages/flutter/lib/src/widgets/animated_list.dart#L992

i think you can copy all of the code to local and relpace SliverList to ExtendedSliverList, and public the parameters which you are used

**Comment by wyzard** [comment]
Thank you for your answer. I don't want to rewrite a framework class, because it may break the operation if Google update it.
But thank you for the tip, if our customer want this behaviour I'll try that way temporarily.
