### ISSUE TITLE
list is empty

### ISSUE THREAD

**Issue by CatEatFishs** [fluttercandies/loading_more_list#2]
When I switch requests the LoadMoreList will show error .for this ,Invalid value: Valid value range is empty: 1
The solution is added the judgment where in Loading_more_base file,
this methods
  @override
  T operator [](int index) {
    // TODO: implement []
    if(index<_array.length-1) {
      return _array[index];
    }
  }

**Comment by zmtzawqlp** [comment]
@CatEatFishs  please update the lastest version
