### ISSUE TITLE
Padding for small list (important bug)

### ISSUE THREAD

**Issue by comerc** [fluttercandies/loading_more_list#20]
I have only one item in list, but can scroll list with padding size. It is bug related with my old [pull request](https://github.com/fluttercandies/extended_nested_scroll_view/pull/19). 

only one item in list:
![Снимок экрана от 2020-07-12 18-49-16](https://user-images.githubusercontent.com/1025241/87250860-8382f380-c470-11ea-951c-8448076b5b26.png)

with wrong scroll behavior:
![Снимок экрана от 2020-07-12 18-49-44](https://user-images.githubusercontent.com/1025241/87250865-87167a80-c470-11ea-9a03-aa948ae43ad5.png)

code fragment:
```dart
    return extended.NestedScrollViewInnerScrollPositionKeyWidget(
      widget.scrollPositionKey,
      LoadingMoreCustomScrollView(
        showGlowLeading: false,
        rebuildCustomScrollView: true,
        physics: ClampingScrollPhysics(),
        slivers: [
          LoadingMoreSliverList(SliverListConfig<ItemModel>(
            extendedListDelegate:
                SliverWaterfallFlowDelegateWithFixedCrossAxisCount(
              crossAxisCount: crossAxisCount,
              crossAxisSpacing: 16,
              mainAxisSpacing: 32,
            ),
            itemBuilder: (BuildContext context, ItemModel item, int index) {
              return ShowcaseItem(
                item: item,
              );
            },
            sourceList: widget.sourceList,
            indicatorBuilder: _buildIndicator,
            padding: EdgeInsets.all(16), // !!!!
            lastChildLayoutType: LastChildLayoutType.foot,
          ))
        ],
      ),
    );
```

**Comment by zmtzawqlp** [comment]
may be we can make an issue for nested_scroll_view, i noticed before, but this  behavior is the same as other platform（android), i have checked it in other app.

**Comment by comerc** [comment]
This bug is reproduced for version 3.1.1 :)
