### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'MapEntry<String, I/flutter ( 1131): List<DemoRouteResult>>' in type cast

### ISSUE THREAD

**Issue by zjf8912** [fluttercandies/loading_more_list#26]
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'MapEntry<String,
I/flutter ( 1131): List<DemoRouteResult>>' in type cast

**Comment by zjf8912** [comment]
example运行起来后点击任意一个选项进入不了下一个页面，提示上面的bug

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/loading_more_list/commit/5379ee56d03777b0761a9e81b25ac7a0683348a0
