### ISSUE TITLE
你这东西非常难用，不知道你有没有这种感觉

### ISSUE THREAD

**Issue by YQjiuhao** [fluttercandies/loading_more_list#3]
flutter: #276    Element.updateChild 
package:flutter/…/widgets/framework.dart:2876
flutter: #277    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3935
flutter: #278    Element.rebuild 
package:flutter/…/widgets/framework.dart:3721
flutter: #279    StatelessElement.update 
package:flutter/…/widgets/framework.dart:3981
flutter: #280    Element.updateChild 
package:flutter/…/widgets/framework.dart:2876
flutter: #281    SliverMultiBoxAdaptorElement.updateChild 
package:flutter/…/widgets/sliver.dart:1181
flutter: #282    SliverMultiBoxAdaptorElement.performRebuild.processElement 
package:flutter/…/widgets/sliver.dart:1113
flutter: #283    Iterable.forEach  (dart:core/iterable.dart:277:30)
flutter: #284    SliverMultiBoxAdaptorElement.performRebuild 
package:flutter/…/widgets/sliver.dart:1139
flutter: #285    SliverMultiBoxAdaptorElement.update 
package:flutter/…/widgets/sliver.dart:1084
flutter: #286    Element.updateChild 
package:flutter/…/widgets/framework.dart:2876

**Comment by zmtzawqlp** [comment]
请另请高明
