### ISSUE TITLE
赋值出现类型不匹配

### ISSUE THREAD

**Issue by qinjinze** [fluttercandies/loading_more_list#34]
The argument type 'FFRouteSettings Function({Map<String, dynamic>? arguments, required String name})' can't be assigned to the parameter type 'FFRouteSettings Function({Map<String, dynamic>? arguments, required String name, Widget? notFoundWidget})'.

**Comment by qinjinze** [comment]
getRouteSettings: getRouteSettings,

**Comment by chaochaox1990** [comment]
change  ff_annotation_route_library: 2.0.0 work for me
