### ISSUE TITLE
The argument type 'FFRouteSettings Function({Map<String, dynamic>? arguments, required String name})' can't be assigned to the parameter type 'FFRouteSettings Function({Map<String, dynamic>? arguments, required String name, Widget? notFoundWidget})'. 

### ISSUE THREAD

**Issue by qinjinze** [fluttercandies/loading_more_list#37]
The argument type 'FFRouteSettings Function({Map<String, dynamic>? arguments, required String name})' can't be assigned to the parameter type 'FFRouteSettings Function({Map<String, dynamic>? arguments, required String name, Widget? notFoundWidget})'. 

flutter sdk2.05
dart   2.3
java 16

**Comment by chaochaox1990** [comment]
change  ff_annotation_route_library: 2.0.0 work for me
