### ISSUE TITLE
Add and remove from list

### ISSUE THREAD

**Issue by pastordee** [fluttercandies/loading_more_list#4]
Hi thanks for the good work, If possible can we get the ability to add and remove from the list  and also to refresh an item at a time say the fifth row in the list after edit or update.

**Comment by zmtzawqlp** [comment]
you can call onStateChanged if you want to notify ui change

**Comment by pastordee** [comment]
Ok will try that thanks.

**Comment by pastordee** [comment]
please I have try it and is not working can show me an example with the onStateChanged thanks

**Comment by zmtzawqlp** [comment]
please provide a runable demo to show your purpose . i will check it as soon as possible

**Comment by zmtzawqlp** [comment]
new version add  setstate method

**Comment by zmtzawqlp** [comment]
reopen if still have problem
