### ISSUE TITLE
flutter热重载时 list刷新

### ISSUE THREAD

**Issue by ghost** [fluttercandies/loading_more_list#43]
如题

**Comment by git-xiaocao** [comment]
通过把 LoadingMoreList 改为StatefulWidget 已解决这个问题
因为  `ListConfig` 不是const 构造器 `LoadingMoreBase`也不是const构造器 会在rebuild的时候重新创建一个新的
然后导致每次热重载都要重新请求数据

**Comment by zmtzawqlp** [comment]
但是你的 sourceList 可以保存下来呢，这样就不会了
