### ISSUE TITLE
support bidirectional

### ISSUE THREAD

**Issue by mbfakourii** [fluttercandies/loading_more_list#48]
Hello, can you provide the possibility of bidirectional scrolling?
That is, we scrolled up or down to load more!

**Comment by zmtzawqlp** [comment]
you can use center property of customscrollview, something like a  chat demo, https://github.com/fluttercandies/flutter_challenges/blob/main/lib/chat_sample.dart

**Comment by mbfakourii** [comment]
This method is not good because the below list has a lot of space and it does not have a good shape at first!

![image](https://user-images.githubusercontent.com/20955005/194694251-9190dc0b-1157-4b2d-9418-9925787a1a3b.png)

And it will be good when it has as much data as extra space!
