### ISSUE TITLE
[Bug report] 建议去掉indicator_widget 中的backgroundColor

### ISSUE THREAD

**Issue by 110** [fluttercandies/loading_more_list#56]
### Content

1. 首先这个backgroundColor 没地方用.  我搜了下,貌似没用

3. 但是没用,它自带了个buff, 不传入,它背景色为Colors.grey[200], 就会出现,当主题为dark黑色时,  它背景为灰色,  很蛋疼
```
  Widget _setbackground(bool full, Widget widget, double height) {
    widget = Container(
        width: double.infinity,
        height: height,
        child: widget,
        color: backgroundColor ?? Colors.grey[200],
        alignment: Alignment.center);
    return widget;
  }
```

https://github.com/fluttercandies/loading_more_list/blob/9afe699fbd49f8793f319a40a672d6a8f455a9dd/lib/src/indicator_widget.dart#L160C9-L160C14

@zmtzawqlp  大佬你觉得呢?

**Comment by zmtzawqlp** [comment]
这不是给用户定义的吗？ 而且如果是自己用的话。建议是自己自定义这些状态的组件，毕竟每个公司的产品都是不一样审美的。
