### ISSUE TITLE
[How to use]  LoadingMoreSliverList 封装后，无法正常使用

### ISSUE THREAD

**Issue by lsfern** [fluttercandies/loading_more_list#59]
### Platforms

Android, iOS

### Description

 LoadingMoreSliverList 封装后，无法正常使用

### My code

封装后会有问题
 return LoadingMoreSliverList<T>(SliverListConfig<T>(
          sourceList: sourceList,
          itemBuilder: (context, T bean, int index) =>
              itemBuilder(bean, index)));

直接使用没问题
 LoadingMoreSliverList<SimpleStarBottomCommunityData>(
              SliverListConfig<SimpleStarBottomCommunityData>(
            sourceList: cvm,
            extendedListDelegate: const ExtendedListDelegate(),
            lastChildLayoutType: LastChildLayoutType.fullCrossAxisExtent,
            itemBuilder: (context, bean, int index) => Container(
              width: 100.w,
              height: 200.w,
              color: Colors.red,
            ),
          )),

**Comment by zmtzawqlp** [comment]
请使用7.0.0版本，并且将它设置为 true
https://github.com/fluttercandies/loading_more_list/blob/e9d1c0dee119043bb06fee8b2e690c37af94f847/lib/src/loading_more_sliver_list.dart#L295

**Comment by lsfern** [comment]
> 请使用7.0.0版本，并且将它设置为 true
> 
> https://github.com/fluttercandies/loading_more_list/blob/e9d1c0dee119043bb06fee8b2e690c37af94f847/lib/src/loading_more_sliver_list.dart#L295

问题已解决。

**Comment by lsfern** [comment]
already fix
