### ISSUE TITLE
loadingmore 和 loading 状态的背景色不是透明，怎么改变背景色?

### ISSUE THREAD

**Issue by 98ki** [fluttercandies/loading_more_list#6]
loadingmore 和 loading 状态的背景色不是透明，无法通过父组件的颜色透显，也没有设置的地方

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/loading_more_list/blob/master/example/lib/demo/custom_indicator_demo.dart

**Comment by zmtzawqlp** [comment]
reopen if still have problem

**Comment by palorotolo** [comment]
me too
怎么给item 设置间隔？实现能间隔是背景是透明的。
