### ISSUE TITLE
there is a compiler message

### ISSUE THREAD

**Issue by guqun** [fluttercandies/loading_more_list#7]
Compiler message:
../../../development/flutter/.pub-cache/git/extended_image_library-c005601d2aef37d3f76c33cf8e3c41768ed2fe6f/lib/src/extended_network_image_provider.dart:63:41: Error: Type 'DecoderCallback' not found.
      ExtendedNetworkImageProvider key, DecoderCallback decode) {

**Comment by zmtzawqlp** [comment]
# use following code if your flutter sdk is more than 1.10    
dependency_overrides:
  extended_image_library:
    git:
        url: https://github.com/fluttercandies/extended_image_library.git
        ref: dev
if you are lower than 1.10 ,please remove it
